# Generated by Django 5.2 on 2025-05-02 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jogador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('adversario', models.CharField(max_length=200)),
                ('resultado', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=200)),
                ('bilhetes_vendidos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogadores', models.ManyToManyField(to='jogador.jogador')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogos.jogo')),
            ],
        ),
        migrations.CreateModel(
            name='Bilhete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.IntegerField(default=0)),
                ('setor', models.CharField(max_length=200)),
                ('fila', models.IntegerField(default=0)),
                ('lugar', models.IntegerField(default=0)),
                ('numero', models.IntegerField(default=0)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogos.jogo')),
            ],
        ),
    ]
