# Generated by Django 5.2 on 2025-05-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilhete',
            name='numero',
        ),
        migrations.AddField(
            model_name='jogo',
            name='bilhetes_maximos',
            field=models.IntegerField(default=0),
        ),
    ]
