# Generated by Django 5.2 on 2025-05-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0002_remove_bilhete_numero_jogo_bilhetes_maximos'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilhete',
            name='numero',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='resultado',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
