# Generated by Django 5.2 on 2025-05-15 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0002_noticia_imagem'),
        ('jogos', '0003_bilhete_numero_alter_jogo_resultado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilhete',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bilhete',
            name='preco',
        ),
        migrations.AddField(
            model_name='bilhete',
            name='produtoloja_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='extras.produtoloja'),
            preserve_default=False,
        ),
    ]
