# Generated by Django 5.2 on 2025-05-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0004_remove_bilhete_id_remove_bilhete_preco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilhete',
            name='fila',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bilhete',
            name='setor',
            field=models.IntegerField(default=0),
        ),
    ]
