# Generated by Django 5.2 on 2025-05-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0005_alter_bilhete_fila_alter_bilhete_setor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilhete',
            name='produtoloja_ptr',
        ),
        migrations.AddField(
            model_name='bilhete',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='bilhete',
            name='preco',
            field=models.IntegerField(default=0),
        ),
    ]
