# Generated by Django 5.2 on 2025-05-18 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0006_remove_bilhete_produtoloja_ptr_bilhete_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adversario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('imagem', models.ImageField(default='Adversarios/logo_clube.png', upload_to='Jogos/')),
            ],
        ),
        migrations.AddField(
            model_name='jogo',
            name='imagem',
            field=models.ImageField(default='Jogos/logo_clube.png', upload_to='Jogos/'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='adversario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogos.adversario'),
        ),
    ]
