# Generated by Django 5.2 on 2025-05-18 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0007_adversario_jogo_imagem_alter_jogo_adversario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilhete',
            name='numero',
        ),
    ]
