# Generated by Django 5.2 on 2025-05-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0008_remove_bilhete_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilhete',
            name='fila',
        ),
        migrations.RemoveField(
            model_name='bilhete',
            name='lugar',
        ),
        migrations.RemoveField(
            model_name='bilhete',
            name='setor',
        ),
        migrations.AddField(
            model_name='bilhete',
            name='bancada',
            field=models.CharField(default='', max_length=200),
        ),
    ]
