# Generated by Django 5.2 on 2025-05-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0009_remove_bilhete_fila_remove_bilhete_lugar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilhete',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
