# Generated by Django 5.2 on 2025-05-18 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0010_bilhete_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convocatoria',
            name='jogo',
        ),
        migrations.AddField(
            model_name='jogo',
            name='convocatoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jogos.convocatoria'),
        ),
    ]
