# Generated by Django 5.2.1 on 2025-05-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('noticia_texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('preco', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='Produtos/')),
            ],
        ),
    ]
