# Generated by Django 5.2 on 2025-05-03 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0002_rename_produtos_loja_produto_loja'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produto_Loja',
            new_name='ProdutoLoja',
        ),
    ]
