# Generated by Django 5.2 on 2025-05-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0002_noticia_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(default='Noticias/logo.png', upload_to='Noticias/'),
        ),
    ]
