# Generated by Django 5.2 on 2025-05-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0003_alter_noticia_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoloja',
            name='imagem',
            field=models.ImageField(default='Produtos/logo.png', upload_to='Produtos/'),
        ),
    ]
