# Generated by Django 5.2 on 2025-05-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Opcao', models.ManyToManyField(blank=True, to='forms.opcao')),
                ('Questao', models.ManyToManyField(blank=True, to='forms.questao')),
            ],
        ),
        migrations.CreateModel(
            name='Inquerito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Opcao', models.ManyToManyField(blank=True, to='forms.opcao')),
                ('Questao', models.ManyToManyField(blank=True, to='forms.questao')),
            ],
        ),
    ]
