# Generated by Django 5.2 on 2025-05-18 01:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_inquerito_pergunta_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquerito',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inquerito',
            name='descricao',
            field=models.TextField(blank=True, default=23),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inquerito',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
