# Generated by Django 5.2 on 2025-05-18 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_formulario_inquerito'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='tipo',
            field=models.CharField(choices=[('FECHADA', 'Fechada (escolha de opções)'), ('ABERTA', 'Aberta (resposta livre)')], default='FECHADA', max_length=10),
        ),
        migrations.AlterField(
            model_name='questao',
            name='pub_data',
            field=models.DateTimeField(verbose_name='data de publicação'),
        ),
        migrations.CreateModel(
            name='RespostaAberta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_texto', models.TextField()),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.questao')),
            ],
        ),
    ]
