# Generated by Django 5.2 on 2025-05-18 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_questao_tipo_alter_questao_pub_data_respostaaberta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='Opcao',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='Questao',
        ),
        migrations.AddField(
            model_name='formulario',
            name='nome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questao',
            name='formulario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='forms.formulario'),
        ),
        migrations.AlterField(
            model_name='opcao',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='forms.questao'),
        ),
        migrations.DeleteModel(
            name='RespostaAberta',
        ),
    ]
