# Generated by Django 5.2 on 2025-05-18 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_remove_formulario_opcao_remove_formulario_questao_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inquerito',
        ),
    ]
