# Generated by Django 5.2 on 2025-05-02 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golos', models.IntegerField(default=0)),
                ('assistencias', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('numero', models.IntegerField(default=0)),
                ('data_nascimento', models.DateField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='Jogadores/')),
                ('stats', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jogador.estatistica')),
            ],
        ),
    ]
