# Generated by Django 5.2 on 2025-05-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='nacionalidade',
            field=models.ImageField(blank=True, null=True, upload_to='Bandeiras/'),
        ),
    ]
