# Generated by Django 5.2 on 2025-05-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogador', '0002_alter_jogador_nacionalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='posicao',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
