# Generated by Django 5.2 on 2025-05-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
        ('jogos', '0006_remove_bilhete_produtoloja_ptr_bilhete_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='carrinho_bilhetes',
            field=models.ManyToManyField(blank=True, to='jogos.bilhete'),
        ),
    ]
