# Generated by Django 5.2 on 2025-05-15 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_customuser_carrinho_bilhetes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='carrinho_bilhetes',
            new_name='carrinho_bilhete',
        ),
    ]
